services:

  service:
    container_name: notification_api
    build:
      context: /
      dockerfile: docker/notification_api.Dockerfile
    ports:
      - 8010:8010
    env_file:
      - .env
    depends_on:
      - db

  db:
    container_name: notification_db
    image: postgres:12.0-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env

  rabbitmq:
    image: rabbitmq:3.10.5-management-alpine
    container_name: notification_rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
    env_file:
      - .env

  scheduler:
    container_name: scheduler
    build:
      context: /
      dockerfile: docker/sheduler.Dockerfile
    env_file:
      - .env
    depends_on:
      - db
      - service
    entrypoint: 'python3 /usr/src/scheduler/main.py'

volumes:
  postgres_data:
  rabbitmq_data:
  static_volume:
  media_volume:
