version: "3.7"

services:
  db:
    container_name: notification_db
    image: postgres:12.0-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env

  admin:
    container_name: notification_admin
    build:
      context: ./admin
      dockerfile: ./Dockerfile
    env_file:
      - .env
    volumes:
      - static_volume:/usr/src/static/
      - media_volume:/usr/src/media/
    ports:
      - 8000:8000
    depends_on:
      - db

  rabbitmq:
    image: rabbitmq:3.10.5-management-alpine
    container_name: notification_rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
    env_file:
      - .env

  worker:
    container_name: worker
    build: worker/
    depends_on:
      - db
      - rabbitmq
    env_file:
      - .env

volumes:
  postgres_data:
  rabbitmq_data:
  static_volume:
  media_volume: